# Numpy

This notebook provides an overview of and playground for **NumPy**, a core library for scientific computing in Python. Numpy provides a high-performance multidimensional array object and tools for working with these arrays. 

This tutorial is heavily based on the [NumPy tutorial](http://cs231n.github.io/python-numpy-tutorial/) by Justin Johnson, Volodymyr Kuleshov, and Isaac Caswell for Stanford's course on Convolutional Neural Neworks for Visual Recognition. You can view their original raw notebook [here](https://github.com/kuleshov/cs228-material). 

Please also see the official [numpy reference](https://docs.scipy.org/doc/numpy/reference/) and [quickstart tutorial](https://docs.scipy.org/doc/numpy-1.12.0/user/quickstart.html). If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with NumPy.

To use Numpy, we first need to import the `numpy` package:

In [2]:
import numpy as np

## Arrays

Numpy's main object is a multidimensional array called `np.array`. Unlike traditional Python lists, which can intermix multiple types, all types in a NumPy array must be the same. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. 

In numpy **dimensions** are called **axes**. The number of axes is **rank**.

For example, the coordinates of a point in 3D space `[1, 2, 1]` is an array of **rank 1**, because it has one axis (and that axis has a length of 3).

In [3]:
a = np.array([1,2,1])
print(a)
print("Rank: ", np.ndim(a))
print("Shape: ", np.shape(a))

[1 2 1]
Rank:  1
Shape:  (3,)


In the example below, the numpy array has rank 2 (it is 2-dimensional). The first dimension (axis) has a length of 2, the second dimension has a length of 3.

In [4]:
a = np.array([[ 1., 0., 0.],[ 0., 1., 2.]])
print(a)
print("Rank: ", np.ndim(a))
print("Shape: ", np.shape(a))

[[1. 0. 0.]
 [0. 1. 2.]]
Rank:  2
Shape:  (2, 3)


We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [5]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
print(a)
a[0] = 5                 # Change an element of the array
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[1 2 3]
[5 2 3]


In [6]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
print(b.shape) 
print(b)    
print(b[0, 0], b[0, 1], b[1, 0]) # access elements by row, column

(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 4


A frequent error consists in calling array with multiple numeric arguments, rather than providing a single list of numbers as an argument.

In [8]:
# This cell will throw an exception
a = np.array(1,2,3,4)    # WRONG, will throw an exception
a = np.array([1,2,3,4])  # RIGHT

ValueError: only 2 non-keyword arguments accepted

## Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to infer a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])                  # Let numpy choose the datatype
y = np.array([1.0, 2.0])              # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [ ]:
import math
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,math.pi,3) # Return evenly spaced numbers over a specified interval.
print(a.dtype, a)
print(b.dtype, b)

c = a + b
print(c.dtype, c)

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

## Creating Arrays
Numpy also provides many functions to create arrays:

In [ ]:
# arange returns evenly spaced values within a given interval.
# see: https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html
a = np.arange(6)                 # 1d array
print(a)

b = np.arange(12).reshape(4,3)   # 2d array
print(b)

c = np.arange(24).reshape(2,3,4) # 3d array
print(c)

In [ ]:
# you can also give arange a step size, which defaults to 1
print(np.arange(1,5))
print(np.arange(1,5,0.5))


In [ ]:
a = np.zeros((2,2))  # Create an array of 2x2 of all zeros
print(a)

print(np.zeros((3,2))) # a 3 rows x 2 columns array of zeros
print(np.zeros((2,4))) # a 2 rows x 4 columns array of zeros

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

print(np.ones((3,2))) # a 3 rows x 2 columns array of ones
print(np.ones((2,4))) # a 2 rows x 4 columns array of ones

In [ ]:
c = np.full((2,2), 7) # Create a constant array
print(c)

c = np.full((2,2), 1) # Same as np.ones((2,2))
print(c)

In [ ]:
d = np.eye(2)        # Create a 2x2 identity matrix
print(d)

d = np.eye(4)        # create a 4x3 identity matrix
print(d)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

e = np.random.random((4,6))
print(e)

e = np.random.random((1,20))
print(e)

## Array Indexing

Numpy offers several ways to index into arrays ([link](https://docs.scipy.org/doc/numpy-1.12.0/user/quickstart.html#indexing-slicing-and-iterating))

### Slicing
Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
# Playing around with slicing (trimming) array
a = np.array([1, 2, 3, 4, 5, 1, 2])
print(a[:4])  # prints [1 2 3 4]
print(a[:1])  # prints [1]
print(a[3:4]) # prints [4]
print(a[1:])  # prints [2 3 4 5 1 2]

In [ ]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

Importantly, a **slice** of an array is a **view** into the **same data**, so modifying it will modify the original array.

In [ ]:
print a[0, 1]  
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print a[0, 1] 

In [ ]:
# To select a row in a 2D array in numpy, use P[i]. For example, P[0] will return the first row of P
# To select a column in a 2D array in numpy, use P[:, i]. The : essentially means "select all rows". 
# For example, P[:, 1] will select all rows from the second column of P.

# this sets columns
a = np.zeros((2,2))
a[:, 0] = [1, 2]   # set column 0 to [1, 2]
print(a)
a[:, 1] = [3, 4]   # set column 1 to [3, 4]
print(a)

# this sets rows
b = np.zeros((2,2))
b[0] = [1, 2]      # set row 0 to [1, 2]
print(b)
b[1] = [3, 4]      # set row 1 to [3, 4]
print(b)

### Integer Array Indexing
When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

### Boolean Array Indexing
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [19]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [20]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


In [21]:
# We can also use boolean array indexing to replace values
a = np.array([1, 2, 3, 4, 5, 1, 2])
a[a > 2] = 0
print(a)

[1 2 0 0 0 1 2]


### Querying Arrays
You can also run queries on the arrays themselves.

In [15]:
# In this example, we show how the numpy 'where' method supports string matching
a = np.array(['apple', 'orange', 'apple', 'banana'])

arr_index = np.where(a == 'apple')
print(a)
print (arr_index)    # prints (array([0, 2]),)
print (a[arr_index]) # prints ['apple' 'apple']

['apple' 'orange' 'apple' 'banana']
(array([0, 2]),)
['apple' 'apple']


In [22]:
# This also works in multiple dimensions
a = np.array([['apple', 'orange', 'apple', 'banana'],['apple', 'apple', 'apple', 'banana']])
arr_index = np.where(a == 'apple')
print(a)
print (arr_index)    
print (a[arr_index])

[['apple' 'orange' 'apple' 'banana']
 ['apple' 'apple' 'apple' 'banana']]
(array([0, 0, 1, 1, 1]), array([0, 2, 0, 1, 2]))
['apple' 'apple' 'apple' 'apple' 'apple']


## Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module (see [link](https://docs.scipy.org/doc/numpy-1.12.0/user/quickstart.html#basic-operations)):

In [65]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the same array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [66]:
# Elementwise difference; both produce the same array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [67]:
# Elementwise product; both produce the same array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [68]:
# Elementwise division; both produce the same array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [99]:
# Elementwise division
a = np.array([1, 2, 3, 4, 5])
half_a = a / 2
print(half_a)

[0.5 1.  1.5 2.  2.5]


In [69]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is **elementwise multiplication**, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [2]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; all produce 219
print(v.dot(w))
print(np.dot(v, w))
print(v @ w)

# Matrix / vector product; all produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

# Matrix / matrix product; all produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

219
219
219
[29 67]
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### Array-Based Arithmetic Operations

In [102]:
# In order for these array-based operations to work, the arrays must be 
# the same size
np1 = np.array([1, 2, 3, 4, 5])
np2 = np.array([1, 2, 4, 7, 5])
np_diff = np2 - np1
print(np_diff)  # prints [0 0 1 3 0]

[0 0 1 3 0]


In [104]:
# This cell will fail due to mismatched sizes
np1 = np.array([1, 2, 3, 4, 5])
np2 = np.array([1, 2, 3])
np_diff = np2 - np1 # this will throw an exception because of shape mismatched sizes


ValueError: operands could not be broadcast together with shapes (3,) (5,) 

In [106]:
# You can resize an array using padding
np1 = np.array([1, 2, 3, 4, 5])
np2 = np.array([1, 2, 3])

# Resize the array by padding. In this case, with zeros
# See: https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html
np2_resized = np.pad(np2, (0, 2), 'constant', constant_values=0)
np_diff = np2_resized - np1
print(np_diff)


[ 0  0  0 -4 -5]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [70]:
x = np.array([[1,2],[3,4]])

print(x)
print(np.sum(x))          # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

## Reshaping Arrays
The simplest of a reshaping operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [71]:
x = np.array([[1,2],[3,4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [72]:
v = np.array([[1,2,3]])
print(v) 
print(v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [74]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v # [i, :] selects the ith row

print(x)
print(v)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector `v` to each row of the matrix `x` is equivalent to forming a matrix `v_tiled` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `v_tiled`. We could implement this approach like this:

In [75]:
v_tiled = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(v_tiled)                 # Prints "[[1 0 1]
                               #          [1 0 1]
                               #          [1 0 1]
                               #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [77]:
y = x + v_tiled  # Add x and vv elementwise
print(x)
print(v_tiled)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of `v`. Consider this version, using broadcasting:

In [78]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [79]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [80]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 4 6]
 [5 7 9]]


In [81]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [82]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [83]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.